(function(){
'use strict';
const $=s=>document.querySelector(s);let stage='tech',mediaReady=false,speakerReady=false,timer;const toast=$('#toast');
if(location.search)TTStudio.applyUrlParams();
const media=new TTMediaController({video:$('#previewVideo'),meter:$('#audioMeter'),cameraSelect:$('#cameraSelect'),micSelect:$('#micSelect'),onStatus(s){mediaReady=!!(s.ready&&s.camera&&s.microphone);$('#previewEmpty').hidden=!!s.camera;set('#cameraStatus',s.camera?'Ready':'Unavailable',!!s.camera);set('#micStatus',s.microphone?'Ready':'Unavailable',!!s.microphone);updateTech()}});
function show(m,e){toast.textContent=m;toast.classList.toggle('error',!!e);toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),2300)}
function set(sel,text,good){const n=$(sel);n.textContent=text;n.classList.toggle('good',good)}
function showStage(next){stage=next;document.querySelectorAll('.stage').forEach(n=>n.classList.toggle('active',n.id===`stage-${next}`));const order=['tech','intro','prep','done'];document.querySelectorAll('.steps button').forEach(b=>{const i=order.indexOf(b.dataset.stage),c=order.indexOf(next);b.classList.toggle('active',i===c);b.classList.toggle('done',i<c);b.querySelector('i').textContent=i<c?'✓':i+1});scrollTo({top:$('.steps').offsetTop-10,behavior:'smooth'})}
function updateTech(){$('#techContinue').disabled=!(mediaReady&&speakerReady)}
function browser(){const good=!!(isSecureContext&&navigator.mediaDevices);set('#browserStatus',good?'Ready':'Needs HTTPS',good)}
function network(){set('#networkStatus',navigator.onLine?'Online':'Offline',navigator.onLine)}
function intro(){const name=$('#guestName').value.trim()||'Guest',title=$('#guestTitle').value.trim(),social=$('#social').value.trim();$('#introPreviewName').textContent=name;$('#introPreviewMeta').textContent=[title,social].filter(Boolean).join(' · ');$('#introPreviewPromo').textContent=$('#promo').value.trim()}
function prepReady(){$('#prepContinue').disabled=![...document.querySelectorAll('.prep-check')].every(x=>x.checked)||!$('#releaseAccepted').checked}
function render(state){const g=state.guest||{};$('#welcomeTitle').innerHTML=`Welcome${g.name&&g.name!=='Future Guest'?', '+g.name:''}.<span>We’ll handle the tech.</span>`;$('#episodeTitle').textContent=`S${state.episode.season} Ep${state.episode.number} · ${state.episode.title}`;$('#episodeMeta').textContent='Private guest check-in';$('#episodeTopic').textContent=state.episode.mainTopic||'';if(document.activeElement!==$('#guestName'))$('#guestName').value=g.name==='Future Guest'?'':g.name||'';if(document.activeElement!==$('#pronouns'))$('#pronouns').value=g.pronouns||'';if(document.activeElement!==$('#guestTitle'))$('#guestTitle').value=g.title||'';if(document.activeElement!==$('#social'))$('#social').value=g.social||'';if(document.activeElement!==$('#promo'))$('#promo').value=g.promo||'';intro()}
function save(){TTStudio.update(n=>{n.guest.name=$('#guestName').value.trim()||'Guest';n.guest.pronouns=$('#pronouns').value.trim();n.guest.title=$('#guestTitle').value.trim();n.guest.social=$('#social').value.trim();n.guest.promo=$('#promo').value.trim();n.guest.status='tech';},'guest-details')}
TTStudio.subscribe(render);browser();network();addEventListener('online',network);addEventListener('offline',network);
$('#testDevices').onclick=async()=>{try{await media.start();show('Camera and microphone are live. Say a few words.')}catch(e){show('Camera or microphone permission is blocked.',true)}};
$('#testSpeaker').onclick=()=>{speakerReady=true;updateTech();show('Headphone check marked ready.')};
$('#techContinue').onclick=()=>{TTStudio.update(n=>{n.guest.status='tech'},'guest-tech');showStage('intro')};$('#introBack').onclick=()=>showStage('tech');
['#guestName','#pronouns','#guestTitle','#social','#promo'].forEach(s=>$(s).oninput=intro);
$('#introContinue').onclick=()=>{save();showStage('prep')};$('#prepBack').onclick=()=>showStage('intro');document.querySelectorAll('.prep-check').forEach(x=>x.onchange=prepReady);$('#releaseAccepted').onchange=prepReady;
$('#prepContinue').onclick=()=>{save();TTStudio.update(n=>{n.guest.releaseAccepted=true;n.guest.ready=true;n.guest.status='ready';n.guest.checkInCompletedAt=new Date().toISOString()},'guest-ready');showStage('done');$('#readyPill').classList.add('ready');$('#readyPill').querySelector('span').textContent='Ready'};
$('#enterStudio').onclick=async()=>{TTStudio.update(n=>{n.guest.status='waiting';n.guest.waitingSince=new Date().toISOString();n.guest.admitted=false},'guest-waiting');await media.stop();(()=>{const q=new URLSearchParams(location.search);const u=new URL('guest-room.html',location.href);['room','token'].forEach(k=>{if(q.get(k))u.searchParams.set(k,q.get(k))});location.href=u.href})()};
addEventListener('beforeunload',()=>media.destroy());
})();